<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130412170532 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE rpg_characters (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, race_id INT DEFAULT NULL, gender_id INT DEFAULT NULL, job_id INT DEFAULT NULL, stats_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, level INT NOT NULL, experience INT NOT NULL, baseStats_id INT DEFAULT NULL, INDEX IDX_E61F7B6A76ED395 (user_id), INDEX IDX_E61F7B66E59D40D (race_id), INDEX IDX_E61F7B6708A0E0 (gender_id), INDEX IDX_E61F7B6BE04EA9 (job_id), UNIQUE INDEX UNIQ_E61F7B6C9920ECD (baseStats_id), UNIQUE INDEX UNIQ_E61F7B670AA3482 (stats_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rpg_char_stats (id INT AUTO_INCREMENT NOT NULL, hp INT NOT NULL, maxhp INT NOT NULL, sp INT NOT NULL, maxsp INT NOT NULL, strength SMALLINT NOT NULL, defense SMALLINT NOT NULL, intelligence SMALLINT NOT NULL, magicdef SMALLINT NOT NULL, accuracy SMALLINT NOT NULL, evasion SMALLINT NOT NULL, magicevasion SMALLINT NOT NULL, speed SMALLINT NOT NULL, luck SMALLINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rpg_equipment (id INT AUTO_INCREMENT NOT NULL, character_id INT DEFAULT NULL, item_id INT DEFAULT NULL, slot SMALLINT NOT NULL, itemData LONGTEXT NOT NULL COMMENT '(DC2Type:array)', INDEX IDX_F55791EA1136BE75 (character_id), INDEX IDX_F55791EA126F525E (item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rpg_genders (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, statsInit LONGTEXT NOT NULL COMMENT '(DC2Type:array)', statsBonus LONGTEXT NOT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rpg_items (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rpg_jobs (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, requirements LONGTEXT NOT NULL COMMENT '(DC2Type:array)', equippableGroups LONGTEXT NOT NULL COMMENT '(DC2Type:array)', statsInit LONGTEXT NOT NULL COMMENT '(DC2Type:array)', statsBonus LONGTEXT NOT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rpg_races (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, statsInit LONGTEXT NOT NULL COMMENT '(DC2Type:array)', statsBonus LONGTEXT NOT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rpg_races_genders (race_id INT NOT NULL, gender_id INT NOT NULL, INDEX IDX_C259969E6E59D40D (race_id), INDEX IDX_C259969E708A0E0 (gender_id), PRIMARY KEY(race_id, gender_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rpg_races_jobs (race_id INT NOT NULL, job_id INT NOT NULL, INDEX IDX_57AE4F3A6E59D40D (race_id), INDEX IDX_57AE4F3ABE04EA9 (job_id), PRIMARY KEY(race_id, job_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rpg_users (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, characterCount SMALLINT NOT NULL, money INT NOT NULL, UNIQUE INDEX UNIQ_F564F4D092FC23A8 (username_canonical), UNIQUE INDEX UNIQ_F564F4D0A0D96FBF (email_canonical), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE rpg_characters ADD CONSTRAINT FK_E61F7B6A76ED395 FOREIGN KEY (user_id) REFERENCES rpg_users (id)");
        $this->addSql("ALTER TABLE rpg_characters ADD CONSTRAINT FK_E61F7B66E59D40D FOREIGN KEY (race_id) REFERENCES rpg_races (id)");
        $this->addSql("ALTER TABLE rpg_characters ADD CONSTRAINT FK_E61F7B6708A0E0 FOREIGN KEY (gender_id) REFERENCES rpg_genders (id)");
        $this->addSql("ALTER TABLE rpg_characters ADD CONSTRAINT FK_E61F7B6BE04EA9 FOREIGN KEY (job_id) REFERENCES rpg_jobs (id)");
        $this->addSql("ALTER TABLE rpg_characters ADD CONSTRAINT FK_E61F7B6C9920ECD FOREIGN KEY (baseStats_id) REFERENCES rpg_char_stats (id)");
        $this->addSql("ALTER TABLE rpg_characters ADD CONSTRAINT FK_E61F7B670AA3482 FOREIGN KEY (stats_id) REFERENCES rpg_char_stats (id)");
        $this->addSql("ALTER TABLE rpg_equipment ADD CONSTRAINT FK_F55791EA1136BE75 FOREIGN KEY (character_id) REFERENCES rpg_characters (id)");
        $this->addSql("ALTER TABLE rpg_equipment ADD CONSTRAINT FK_F55791EA126F525E FOREIGN KEY (item_id) REFERENCES rpg_items (id)");
        $this->addSql("ALTER TABLE rpg_races_genders ADD CONSTRAINT FK_C259969E6E59D40D FOREIGN KEY (race_id) REFERENCES rpg_races (id)");
        $this->addSql("ALTER TABLE rpg_races_genders ADD CONSTRAINT FK_C259969E708A0E0 FOREIGN KEY (gender_id) REFERENCES rpg_genders (id)");
        $this->addSql("ALTER TABLE rpg_races_jobs ADD CONSTRAINT FK_57AE4F3A6E59D40D FOREIGN KEY (race_id) REFERENCES rpg_races (id)");
        $this->addSql("ALTER TABLE rpg_races_jobs ADD CONSTRAINT FK_57AE4F3ABE04EA9 FOREIGN KEY (job_id) REFERENCES rpg_jobs (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE rpg_equipment DROP FOREIGN KEY FK_F55791EA1136BE75");
        $this->addSql("ALTER TABLE rpg_characters DROP FOREIGN KEY FK_E61F7B6C9920ECD");
        $this->addSql("ALTER TABLE rpg_characters DROP FOREIGN KEY FK_E61F7B670AA3482");
        $this->addSql("ALTER TABLE rpg_characters DROP FOREIGN KEY FK_E61F7B6708A0E0");
        $this->addSql("ALTER TABLE rpg_races_genders DROP FOREIGN KEY FK_C259969E708A0E0");
        $this->addSql("ALTER TABLE rpg_equipment DROP FOREIGN KEY FK_F55791EA126F525E");
        $this->addSql("ALTER TABLE rpg_characters DROP FOREIGN KEY FK_E61F7B6BE04EA9");
        $this->addSql("ALTER TABLE rpg_races_jobs DROP FOREIGN KEY FK_57AE4F3ABE04EA9");
        $this->addSql("ALTER TABLE rpg_characters DROP FOREIGN KEY FK_E61F7B66E59D40D");
        $this->addSql("ALTER TABLE rpg_races_genders DROP FOREIGN KEY FK_C259969E6E59D40D");
        $this->addSql("ALTER TABLE rpg_races_jobs DROP FOREIGN KEY FK_57AE4F3A6E59D40D");
        $this->addSql("ALTER TABLE rpg_characters DROP FOREIGN KEY FK_E61F7B6A76ED395");
        $this->addSql("DROP TABLE rpg_characters");
        $this->addSql("DROP TABLE rpg_char_stats");
        $this->addSql("DROP TABLE rpg_equipment");
        $this->addSql("DROP TABLE rpg_genders");
        $this->addSql("DROP TABLE rpg_items");
        $this->addSql("DROP TABLE rpg_jobs");
        $this->addSql("DROP TABLE rpg_races");
        $this->addSql("DROP TABLE rpg_races_genders");
        $this->addSql("DROP TABLE rpg_races_jobs");
        $this->addSql("DROP TABLE rpg_users");
    }
}
