<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130519122433 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE rpg_char_jobs (id INT AUTO_INCREMENT NOT NULL, character_id INT DEFAULT NULL, job_id INT DEFAULT NULL, level SMALLINT NOT NULL, experience INT NOT NULL, INDEX IDX_FE3957F01136BE75 (character_id), INDEX IDX_FE3957F0BE04EA9 (job_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rpg_char_skills (id INT AUTO_INCREMENT NOT NULL, character_id INT DEFAULT NULL, timesUsed INT NOT NULL, customSkill_id INT DEFAULT NULL, INDEX IDX_B10C5BDE1136BE75 (character_id), INDEX IDX_B10C5BDEDFE22BA4 (customSkill_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rpg_item_types (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rpg_parties (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_518B153AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rpg_skills (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rpg_skill_custom (id INT AUTO_INCREMENT NOT NULL, skill_id INT DEFAULT NULL, INDEX IDX_D4D044CE5585C142 (skill_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE rpg_char_jobs ADD CONSTRAINT FK_FE3957F01136BE75 FOREIGN KEY (character_id) REFERENCES rpg_characters (id)");
        $this->addSql("ALTER TABLE rpg_char_jobs ADD CONSTRAINT FK_FE3957F0BE04EA9 FOREIGN KEY (job_id) REFERENCES rpg_jobs (id)");
        $this->addSql("ALTER TABLE rpg_char_skills ADD CONSTRAINT FK_B10C5BDE1136BE75 FOREIGN KEY (character_id) REFERENCES rpg_characters (id)");
        $this->addSql("ALTER TABLE rpg_char_skills ADD CONSTRAINT FK_B10C5BDEDFE22BA4 FOREIGN KEY (customSkill_id) REFERENCES rpg_skill_custom (id)");
        $this->addSql("ALTER TABLE rpg_parties ADD CONSTRAINT FK_518B153AA76ED395 FOREIGN KEY (user_id) REFERENCES rpg_users (id)");
        $this->addSql("ALTER TABLE rpg_skill_custom ADD CONSTRAINT FK_D4D044CE5585C142 FOREIGN KEY (skill_id) REFERENCES rpg_skills (id)");
        $this->addSql("ALTER TABLE rpg_characters ADD party_id INT DEFAULT NULL, ADD partyPosition SMALLINT NOT NULL");
        $this->addSql("ALTER TABLE rpg_characters ADD CONSTRAINT FK_E61F7B6213C1059 FOREIGN KEY (party_id) REFERENCES rpg_parties (id)");
        $this->addSql("CREATE INDEX IDX_E61F7B6213C1059 ON rpg_characters (party_id)");
        $this->addSql("ALTER TABLE rpg_items ADD stackSize SMALLINT NOT NULL, ADD modifiers LONGTEXT NOT NULL COMMENT '(DC2Type:array)', ADD itemType_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE rpg_items ADD CONSTRAINT FK_F9B874753B2743 FOREIGN KEY (itemType_id) REFERENCES rpg_item_types (id)");
        $this->addSql("CREATE INDEX IDX_F9B874753B2743 ON rpg_items (itemType_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE rpg_items DROP FOREIGN KEY FK_F9B874753B2743");
        $this->addSql("ALTER TABLE rpg_characters DROP FOREIGN KEY FK_E61F7B6213C1059");
        $this->addSql("ALTER TABLE rpg_skill_custom DROP FOREIGN KEY FK_D4D044CE5585C142");
        $this->addSql("ALTER TABLE rpg_char_skills DROP FOREIGN KEY FK_B10C5BDEDFE22BA4");
        $this->addSql("DROP TABLE rpg_char_jobs");
        $this->addSql("DROP TABLE rpg_char_skills");
        $this->addSql("DROP TABLE rpg_item_types");
        $this->addSql("DROP TABLE rpg_parties");
        $this->addSql("DROP TABLE rpg_skills");
        $this->addSql("DROP TABLE rpg_skill_custom");
        $this->addSql("DROP INDEX IDX_E61F7B6213C1059 ON rpg_characters");
        $this->addSql("ALTER TABLE rpg_characters DROP party_id, DROP partyPosition");
        $this->addSql("DROP INDEX IDX_F9B874753B2743 ON rpg_items");
        $this->addSql("ALTER TABLE rpg_items DROP stackSize, DROP modifiers, DROP itemType_id");
    }
}
