<?php

namespace Maroon\RPGBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkillCustomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillCustomRepository extends EntityRepository
{
}
